import Head from "next/head";
import { Inter } from "next/font/google";
import { useSession } from "next-auth/react";
import { useEffect, useMemo } from "react";
import { Route } from "@/constants/route";
import { Carousel, Layout, Space } from "antd";
import styles from "./styles.module.scss";
import { images } from "../../public/images";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: _session, status: _ } = useSession();

  const banners = useMemo(() => {
    return [images.banner1, images.banner2, images.banner3];
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Space direction="vertical" className={styles.container}>
        <Layout className={styles.layout}>
          <Carousel
            autoplay
            dots={false}
            dotPosition="bottom"
            autoplaySpeed={3000}
            pauseOnFocus={false}
            pauseOnHover={false}
            pauseOnDotsHover={false}
          >
            {banners.map((banner, index: number) => (
              <Image
                src={banner}
                alt={`banner${index + 1}`}
                key={index}
                className={styles.banner}
              />
            ))}
          </Carousel>
        </Layout>
      </Space>
    </>
  );
}
